import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Providers } from './GlobalRedux/provider';
import AuthProvider from '@/components/auth/AuthProvider';
import { Select, initTE } from "tw-elements";
const inter = Poppins({ subsets: ['latin'], weight: '400' });


export const metadata: Metadata = {
  title: 'intellectx',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  
      <html lang="en">
        <body className={inter.className}>
    

          
        <Providers>
        {children}
        </Providers>
   
          </body>
      </html>
   
  );
}
