apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-depl
spec:
  replicas: 2 
  selector: 
    matchLabels:
      app: communication 
  template: 
    metadata: 
      labels:
        app: communication
    spec:
      containers:
        - name: communication
          image: anshadkt/communication
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: my-env-secret3
                  key: MONGO_URI
            - name: JWT_KEY 
              valueFrom: 
                secretKeyRef:
                  name: my-env-secret3
                  key: JWT_KEY

---  
apiVersion: v1
kind: Service
metadata:
  name: communication-srv
spec:
  selector:
    app: communication
  ports:
    - name: communication
      protocol: TCP
      port: 3000
      targetPort: 3000
