apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication1
  template:
    metadata:
      labels:
        app: communication1
    spec:
      containers:
        - name: communication1
          image: anshadkt/communication1
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: my-env-secret3
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-env-secret3
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: communication1-srv
spec:
  selector:
    app: communication1
  ports:
    - name: communication1
      protocol: TCP
      port: 3000
      targetPort: 3000
