apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant 
  template: 
    metadata:
      labels:
        app: tenant  
    spec: 
      containers:
        - name: tenant
          image: anshadkt/tenant
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: my-env-secret2
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-env-secret2
                  key: JWT_KEY
            - name: NODEPASS
              valueFrom:
                secretKeyRef:
                  name: my-env-secret2
                  key: NODEPASS

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-srv
spec:
  selector:
    app: tenant
  ports:
    - name: tenant
      protocol: TCP
      port: 3000
      targetPort: 3000
