apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant1
  template:
    metadata:
      labels:
        app: tenant1
    spec:
      containers:
        - name: tenant1
          image: anshadkt/tenant1
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: my-env-secret2
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-env-secret2
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tenant1-srv
spec:
  selector:
    app: tenant1
  ports:
    - name: tenant1
      protocol: TCP
      port: 3000
      targetPort: 3000
