name: deploy-manifests

on: 
  push:
    branches:  
      - master
    paths: 
      - 'infra/**'
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:   
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN3 }}
      - run: doctl kubernetes cluster kubeconfig save intellectx-cluster3
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
