name: deploy-tenant

on: 
  push:
    branches: 
      - master
    paths:
      - 'tenant/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd tenant && docker build -t anshadkt/tenant .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push anshadkt/tenant
